// Generated by jextract

package org.eclipse.core.internal.filesystem.local.linux.ffm;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SequenceLayout;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

public class dirent {

	dirent() {
		// Should not be called directly
	}

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout( //
			LinuxDirent.C_LONG.withName("d_ino"), //$NON-NLS-1$
			LinuxDirent.C_LONG.withName("d_off"), //$NON-NLS-1$
			LinuxDirent.C_SHORT.withName("d_reclen"), //$NON-NLS-1$
			LinuxDirent.C_CHAR.withName("d_type"), //$NON-NLS-1$
			MemoryLayout.sequenceLayout(256, LinuxDirent.C_CHAR).withName("d_name"), //$NON-NLS-1$
			MemoryLayout.paddingLayout(5 * 8L)) //
			.withName("dirent"); //$NON-NLS-1$

	public static GroupLayout layout() {
		return $LAYOUT;
	}

	private static final SequenceLayout d_name$LAYOUT = (SequenceLayout) $LAYOUT.select(groupElement("d_name")); //$NON-NLS-1$
	private static final long d_name$OFFSET = $LAYOUT.byteOffset(groupElement("d_name")); //$NON-NLS-1$

	public static SequenceLayout d_name$layout() {
		return d_name$LAYOUT;
	}

	public static long d_name$offset() {
		return d_name$OFFSET;
	}

	public static MemorySegment d_name(MemorySegment struct) {
		return struct.asSlice(d_name$OFFSET, d_name$LAYOUT.byteSize());
	}
}
