// Generated by jextract

package org.eclipse.core.internal.filesystem.local.linux.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandle;

public class LinuxDirent extends LinuxDirent$shared {

	LinuxDirent() {
		// Should not be called directly
	}

	static final Arena LIBRARY_ARENA = Arena.ofAuto();

	static final SymbolLookup SYMBOL_LOOKUP = loaderLookup();

	private static SymbolLookup loaderLookup() {
		try {
			return SymbolLookup.libraryLookup(System.mapLibraryName("c"), LIBRARY_ARENA) //$NON-NLS-1$
					.or(SymbolLookup.loaderLookup()) //
					.or(Linker.nativeLinker().defaultLookup());
		} catch (RuntimeException | LinkageError e) {
			return SymbolLookup.loaderLookup().or(Linker.nativeLinker().defaultLookup());
		}
	}

	private static final int ENOENT = 2;

	public static int ENOENT() {
		return ENOENT;
	}

	private static final int AT_SYMLINK_NOFOLLOW = 256;

	public static int AT_SYMLINK_NOFOLLOW() {
		return AT_SYMLINK_NOFOLLOW;
	}

	private static final int PATH_MAX = 4096;

	public static int PATH_MAX() {
		return PATH_MAX;
	}

	private static final int S_IFMT = 0170000;

	public static int S_IFMT() {
		return S_IFMT;
	}

	private static final int S_IFLNK = 0120000;

	public static int S_IFLNK() {
		return S_IFLNK;
	}

	private static final int S_IFDIR = 0040000;

	public static int S_IFDIR() {
		return S_IFDIR;
	}

	private static final int S_IRUSR = 0400;

	public static int S_IRUSR() {
		return S_IRUSR;
	}

	private static final int S_IWUSR = 0200;

	public static int S_IWUSR() {
		return S_IWUSR;
	}

	private static final int S_IXUSR = 0100;

	public static int S_IXUSR() {
		return S_IXUSR;
	}

	private static final int S_IRGRP = 040;

	public static int S_IRGRP() {
		return S_IRGRP;
	}

	private static final int S_IWGRP = 020;

	public static int S_IWGRP() {
		return S_IWGRP;
	}

	private static final int S_IXGRP = 010;

	public static int S_IXGRP() {
		return S_IXGRP;
	}

	private static final int S_IROTH = 04;

	public static int S_IROTH() {
		return S_IROTH;
	}

	private static final int S_IWOTH = 02;

	public static int S_IWOTH() {
		return S_IWOTH;
	}

	private static final int S_IXOTH = 01;

	public static int S_IXOTH() {
		return S_IXOTH;
	}

	private static class opendir {
		static final FunctionDescriptor DESC = FunctionDescriptor.of(C_POINTER, C_POINTER);
		static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("opendir"); //$NON-NLS-1$
		static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	public static FunctionDescriptor opendir$descriptor() {
		return opendir.DESC;
	}

	public static MethodHandle opendir$handle() {
		return opendir.HANDLE;
	}

	public static MemorySegment opendir$address() {
		return opendir.ADDR;
	}

	public static MemorySegment opendir(MemorySegment name) {
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("opendir", name); //$NON-NLS-1$
			}
			return (MemorySegment) opendir.HANDLE.invokeExact(name);
		} catch (Error | RuntimeException e) {
			throw e;
		} catch (Throwable e) {
			throw new AssertionError("should not reach here", e); //$NON-NLS-1$
		}
	}

	private static class readdir {
		static final FunctionDescriptor DESC = FunctionDescriptor.of(C_POINTER, C_POINTER);
		static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("readdir"); //$NON-NLS-1$
		static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	public static FunctionDescriptor readdir$descriptor() {
		return readdir.DESC;
	}

	public static MethodHandle readdir$handle() {
		return readdir.HANDLE;
	}

	public static MemorySegment readdir$address() {
		return readdir.ADDR;
	}

	public static MemorySegment readdir(MemorySegment dirp) {
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("readdir", dirp); //$NON-NLS-1$
			}
			return (MemorySegment) readdir.HANDLE.invokeExact(dirp);
		} catch (Error | RuntimeException e) {
			throw e;
		} catch (Throwable e) {
			throw new AssertionError("should not reach here", e); //$NON-NLS-1$
		}
	}

	private static class closedir {
		static final FunctionDescriptor DESC = FunctionDescriptor.of(C_INT, C_POINTER);
		static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("closedir"); //$NON-NLS-1$
		static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	public static FunctionDescriptor closedir$descriptor() {
		return closedir.DESC;
	}

	public static MethodHandle closedir$handle() {
		return closedir.HANDLE;
	}

	public static MemorySegment closedir$address() {
		return closedir.ADDR;
	}

	public static int closedir(MemorySegment dirp) {
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("closedir", dirp); //$NON-NLS-1$
			}
			return (int) closedir.HANDLE.invokeExact(dirp);
		} catch (Error | RuntimeException e) {
			throw e;
		} catch (Throwable e) {
			throw new AssertionError("should not reach here", e); //$NON-NLS-1$
		}
	}

	private static class dirfd {
		static final FunctionDescriptor DESC = FunctionDescriptor.of(C_INT, C_POINTER);
		static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("dirfd"); //$NON-NLS-1$
		static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	public static FunctionDescriptor dirfd$descriptor() {
		return dirfd.DESC;
	}

	public static MethodHandle dirfd$handle() {
		return dirfd.HANDLE;
	}

	public static MemorySegment dirfd$address() {
		return dirfd.ADDR;
	}

	public static int dirfd(MemorySegment dirp) {
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("dirfd", dirp); //$NON-NLS-1$
			}
			return (int) dirfd.HANDLE.invokeExact(dirp);
		} catch (Error | RuntimeException e) {
			throw e;
		} catch (Throwable e) {
			throw new AssertionError("should not reach here", e); //$NON-NLS-1$
		}
	}

	private static class fstatat {
		static final FunctionDescriptor DESC = FunctionDescriptor.of(C_INT, C_INT, C_POINTER, C_POINTER, C_INT);
		static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("fstatat"); //$NON-NLS-1$
		static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	public static FunctionDescriptor fstatat$descriptor() {
		return fstatat.DESC;
	}

	public static MethodHandle fstatat$handle() {
		return fstatat.HANDLE;
	}

	public static MemorySegment fstatat$address() {
		return fstatat.ADDR;
	}

	public static int fstatat(int dirfd, MemorySegment pathname, MemorySegment statbuf, int flags) {
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("fstatat", dirfd, pathname, statbuf, flags); //$NON-NLS-1$
			}
			return (int) fstatat.HANDLE.invokeExact(dirfd, pathname, statbuf, flags);
		} catch (Error | RuntimeException e) {
			throw e;
		} catch (Throwable e) {
			throw new AssertionError("should not reach here", e); //$NON-NLS-1$
		}
	}

	private static class readlinkat {
		static final FunctionDescriptor DESC = FunctionDescriptor.of(C_LONG, C_INT, C_POINTER, C_POINTER, C_LONG);
		static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("readlinkat"); //$NON-NLS-1$
		static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	public static FunctionDescriptor readlinkat$descriptor() {
		return readlinkat.DESC;
	}

	public static MethodHandle readlinkat$handle() {
		return readlinkat.HANDLE;
	}

	public static MemorySegment readlinkat$address() {
		return readlinkat.ADDR;
	}

	public static long readlinkat(int dirfd, MemorySegment pathname, MemorySegment buf, long bufsiz) {
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("readlinkat", dirfd, pathname, buf, bufsiz); //$NON-NLS-1$
			}
			return (long) readlinkat.HANDLE.invokeExact(dirfd, pathname, buf, bufsiz);
		} catch (Error | RuntimeException e) {
			throw e;
		} catch (Throwable e) {
			throw new AssertionError("should not reach here", e); //$NON-NLS-1$
		}
	}
}
