// Generated by jextract

package org.eclipse.core.internal.filesystem.local.linux.ffm;

import java.lang.foreign.Linker;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;

public class LinuxDirent$shared {

	LinuxDirent$shared() {
		// Should not be called directly
	}

	public static final ValueLayout.OfBoolean C_BOOL = (ValueLayout.OfBoolean) Linker.nativeLinker().canonicalLayouts().get("bool"); //$NON-NLS-1$
	public static final ValueLayout.OfByte C_CHAR = (ValueLayout.OfByte) Linker.nativeLinker().canonicalLayouts().get("char"); //$NON-NLS-1$
	public static final ValueLayout.OfShort C_SHORT = (ValueLayout.OfShort) Linker.nativeLinker().canonicalLayouts().get("short"); //$NON-NLS-1$
	public static final ValueLayout.OfInt C_INT = (ValueLayout.OfInt) Linker.nativeLinker().canonicalLayouts().get("int"); //$NON-NLS-1$
	public static final ValueLayout.OfLong C_LONG_LONG = (ValueLayout.OfLong) Linker.nativeLinker().canonicalLayouts().get("long long"); //$NON-NLS-1$
	public static final ValueLayout.OfFloat C_FLOAT = (ValueLayout.OfFloat) Linker.nativeLinker().canonicalLayouts().get("float"); //$NON-NLS-1$
	public static final ValueLayout.OfDouble C_DOUBLE = (ValueLayout.OfDouble) Linker.nativeLinker().canonicalLayouts().get("double"); //$NON-NLS-1$
	public static final java.lang.foreign.AddressLayout C_POINTER = (java.lang.foreign.AddressLayout) Linker.nativeLinker().canonicalLayouts().get("void*"); //$NON-NLS-1$
	public static final ValueLayout.OfLong C_LONG = (ValueLayout.OfLong) Linker.nativeLinker().canonicalLayouts().get("long"); //$NON-NLS-1$
	public static final ValueLayout.OfDouble C_LONG_DOUBLE = (ValueLayout.OfDouble) Linker.nativeLinker().canonicalLayouts().get("double"); //$NON-NLS-1$

	static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls"); //$NON-NLS-1$

	static void traceDowncall(String name, Object... args) {
		System.out.println("downcall: " + name + "(" + java.util.stream.Stream.of(args).map(String::valueOf).collect(java.util.stream.Collectors.joining(", ")) + ")"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
	}

	static MethodHandle upcallHandle(Class<?> fi, String name, java.lang.foreign.FunctionDescriptor fdesc) {
		try {
			return java.lang.invoke.MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
		} catch (ReflectiveOperationException ex) {
			throw new AssertionError(ex);
		}
	}
}
