// Generated by jextract

package org.eclipse.core.internal.filesystem.local.linux.ffm;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

public class stat {

	stat() {
		// Should not be called directly
	}

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout( //
			MemoryLayout.paddingLayout(24 * 8L), //
			LinuxDirent.C_INT.withName("st_mode"), //$NON-NLS-1$
			MemoryLayout.paddingLayout(20 * 8L), //
			LinuxDirent.C_LONG.withName("st_size"), //$NON-NLS-1$
			MemoryLayout.paddingLayout(32 * 8L), //
			timespec.layout().withName("st_mtim"), //$NON-NLS-1$
			MemoryLayout.paddingLayout(40 * 8L)) //
			.withByteAlignment(8) //
			.withName("stat"); //$NON-NLS-1$

	public static GroupLayout layout() {
		return $LAYOUT;
	}

	private static final ValueLayout.OfInt st_mode$LAYOUT = (ValueLayout.OfInt) $LAYOUT.select(groupElement("st_mode")); //$NON-NLS-1$
	private static final long st_mode$OFFSET = $LAYOUT.byteOffset(groupElement("st_mode")); //$NON-NLS-1$
	private static final ValueLayout.OfLong st_size$LAYOUT = (ValueLayout.OfLong) $LAYOUT.select(groupElement("st_size")); //$NON-NLS-1$
	private static final long st_size$OFFSET = $LAYOUT.byteOffset(groupElement("st_size")); //$NON-NLS-1$
	private static final GroupLayout st_mtim$LAYOUT = (GroupLayout) $LAYOUT.select(groupElement("st_mtim")); //$NON-NLS-1$
	private static final long st_mtim$OFFSET = $LAYOUT.byteOffset(groupElement("st_mtim")); //$NON-NLS-1$

	public static int st_mode(MemorySegment struct) {
		return struct.get(st_mode$LAYOUT, st_mode$OFFSET);
	}

	public static long st_size(MemorySegment struct) {
		return struct.get(st_size$LAYOUT, st_size$OFFSET);
	}

	public static MemorySegment st_mtim(MemorySegment struct) {
		return struct.asSlice(st_mtim$OFFSET, st_mtim$LAYOUT.byteSize());
	}
}
