// Generated by jextract

package org.eclipse.core.internal.filesystem.local.linux.ffm;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

public class timespec {

	timespec() {
		// Should not be called directly
	}

	private static final GroupLayout $LAYOUT = MemoryLayout.structLayout( //
			LinuxDirent.C_LONG.withName("tv_sec"), //$NON-NLS-1$
			LinuxDirent.C_LONG.withName("tv_nsec")) //$NON-NLS-1$
			.withName("timespec"); //$NON-NLS-1$

	public static GroupLayout layout() {
		return $LAYOUT;
	}

	private static final ValueLayout.OfLong tv_sec$LAYOUT = (ValueLayout.OfLong) $LAYOUT.select(groupElement("tv_sec")); //$NON-NLS-1$
	private static final long tv_sec$OFFSET = $LAYOUT.byteOffset(groupElement("tv_sec")); //$NON-NLS-1$
	private static final ValueLayout.OfLong tv_nsec$LAYOUT = (ValueLayout.OfLong) $LAYOUT.select(groupElement("tv_nsec")); //$NON-NLS-1$
	private static final long tv_nsec$OFFSET = $LAYOUT.byteOffset(groupElement("tv_nsec")); //$NON-NLS-1$

	public static long tv_sec(MemorySegment struct) {
		return struct.get(tv_sec$LAYOUT, tv_sec$OFFSET);
	}

	public static long tv_nsec(MemorySegment struct) {
		return struct.get(tv_nsec$LAYOUT, tv_nsec$OFFSET);
	}
}
