# Fast running checks for pull-requests

name: Pull-Request Checks
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '5 0 * * *' # once daily (avoid peek loads at the beginning of the day)

jobs:
  check-freeze-period:
    if: github.event_name == 'pull_request'
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/verifyFreezePeriod.yml@master
  check-merge-commits:
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/checkMergeCommits.yml@master
  check-versions:
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/checkVersions.yml@master
    with:
      botName: Eclipse Platform Bot
      botMail: platform-bot@eclipse.org
